export { default as ContactView } from "./ContactView.vue"
export { default as CalculatorView } from "./CalculatorView.vue"
export { default as RegisterView } from "./RegisterView.vue"
export { default as LoginView } from "./LoginView.vue"
export { default as ProfileView } from "./ProfileView.vue"
